### PR TITLE
Adding a GetInt function to envy

### PR DESCRIPTION
**Pull request by arschles**

### CODE REVIEW

**Comment by arschles** [comment]
Is this ok to merge?

**Comment by robbyoconnor** [comment]
I can't merge it -- I just said it looked okay...

**Comment by arschles** [comment]
Ah got it. Sorry for the mixup, and thank you for reviewing it!

Sorry about my wording - I certainly didnt mean to come off rude. Cheers :)

**Comment by robbyoconnor** [comment]
No issues!

**Comment by markbates** [comment]
TBH, I'm not a fan of this PR, sorry. Let me explain why. 

First, the first part of the method is something that `envy.Get` already does, so all that `GetInt` really does is save 1 error check in someone's code. Not sure it's worth it, tbh.

Plus, if we add `GetInt`, then what about all the other types? What about `GetBool`, `GetFloat`, etc... I think you start to go down a big rabbit hole by introducing this method.

In Buffalo, for example, I originally had a `ParamInt` function on the context, that did a very similar thing, eventually it was ripped out for the reasons above.

Thank you for the time spent on this PR, and hopefully, I haven't discouraged you from submitting another one.

**Pull request closed without merging**
