### PR TITLE
fix gh-16: check for "test.v" flag to be defined, but don't check its…

### PR DESCRIPTION
**Pull request by armhold**
… value

### CODE REVIEW

**Comment by markbates** [comment]
Thanks!

**Comment by stanislas-m** [comment]
@markbates It was changed in #15, did you make sure the reported case still works with this PR?

**Comment by markbates** [comment]
@stanislas-m ah, good catch. I haven't done the release yet, but I'll test it now.

**Comment by markbates** [comment]
@stanislas-m I can confirm this doesn't break that.

**Comment by armhold** [comment]
Ah, sorry, I wasn't familiar with the history; I should have checked.

In any case, I think the solution introduced by gh-15 is not correct, as it was effectively testing for running under a unit test *with the verbose flag*. I don't think that's what is intended. There is a [stackoverflow answer](https://stackoverflow.com/a/44716385/93995) that is misleading people (myself included!)

Not sure what was causing the breakage reported in gh-15, but I suspect the fix was an accidental side effect.

**Pull request merged**
