### PR TITLE
require explicit Load

### PR DESCRIPTION
**Pull request by twpayne**
Before this change, Load was always called in `init()`. This made it impossible to avoid replacing environment variables with values from `.env` in any program that imports `envy`, directly or indirectly.

See https://github.com/gobuffalo/packr/issues/191 for an example of where this causes problems.

After this change, programs that want this behavior can explicitly activate it by calling `envy.Load` in their `init() `functions.

This PR effectively reverts 15f5083a6e269f8698715b13dd25f0538754ab37.

### CODE REVIEW

**Comment by markbates** [comment]
This is a breaking change, and needs to be considered as such.

**Comment by twpayne** [comment]
FWIW I've forked `envy` to fix this problem: https://github.com/airmap/envy.

You can use the fixed `envy` by adding the following to your `go.mod` file:

```
replace github.com/gobuffalo/envy => github.com/airmap/envy v1.6.16
```

**Comment by mellis** [comment]
The current `init()` behaviour also breaks in go 1.13 (you can no longer lookup the `test.v` flag in `init()`. This should be done in `TestMain()`). See https://github.com/golang/go/issues/31859

**Comment by twpayne** [comment]
I guess this will not be fixed. Closing this issue to prevent it cluttering my list of open pull requests.

**Pull request closed without merging**
